export type BDArea = {
  name: string;
  subAreas?: string[];
};

export type BDAreaGroup = {
  label: string;
  areas: BDArea[];
};

export const BD_AREAS: BDAreaGroup[] = [
  {
    label: "Dhaka",
    areas: [
      { name: "Gulshan", subAreas: ["Gulshan 1", "Gulshan 2", "Gulshan Avenue"] },
      { name: "Banani", subAreas: ["Banani", "Banani DOHS"] },
      {
        name: "Baridhara",
        subAreas: ["Baridhara", "Baridhara DOHS", "Baridhara Diplomatic Zone"],
      },
      {
        name: "Bashundhara R/A",
        subAreas: [
          "Block A",
          "Block B",
          "Block C",
          "Block D",
          "Block E",
          "Block F",
          "Block G",
          "Block H",
          "Block I",
          "Block J",
          "Block K",
        ],
      },
      { name: "Dhanmondi" },
      { name: "Kalabagan" },
      { name: "New Market" },
      { name: "Azimpur" },
      { name: "Elephant Road" },
      {
        name: "Mirpur",
        subAreas: [
          "Mirpur 1",
          "Mirpur 2",
          "Mirpur 6",
          "Mirpur 10",
          "Mirpur 11",
          "Mirpur 12",
          "Mirpur 13",
          "Mirpur 14",
          "Mirpur DOHS",
        ],
      },
      { name: "Kafrul" },
      { name: "Kallyanpur" },
      {
        name: "Uttara",
        subAreas: [
          "Sector 1",
          "Sector 2",
          "Sector 3",
          "Sector 4",
          "Sector 5",
          "Sector 6",
          "Sector 7",
          "Sector 8",
          "Sector 9",
          "Sector 10",
          "Sector 11",
          "Sector 12",
          "Sector 13",
          "Sector 14",
          "Uttara DOHS",
        ],
      },
      { name: "Airport", subAreas: ["Khilkhet", "Nikunja 1", "Nikunja 2"] },
      { name: "Mohakhali", subAreas: ["Mohakhali", "Mohakhali DOHS"] },
      { name: "Tejgaon", subAreas: ["Tejgaon", "Tejgaon Industrial Area"] },
      { name: "Farmgate" },
      { name: "Rampura" },
      { name: "Banasree" },
      { name: "Aftabnagar" },
      { name: "Badda", subAreas: ["Badda", "North Badda", "South Badda", "Middle Badda"] },
      { name: "Vatara" },
      { name: "Mohammadpur", subAreas: ["Mohammadpur", "Mohammadpur Housing Estate"] },
      { name: "Lalmatia" },
      { name: "Shyamoli" },
      { name: "Adabar" },
      { name: "Agargaon" },
      { name: "Sher-e-Bangla Nagar" },
      { name: "Khilgaon" },
      { name: "Basabo" },
      { name: "Pallabi" },
      { name: "Cantonment", subAreas: ["Dhaka Cantonment", "Kurmitola"] },
      { name: "Bosila" },
      { name: "Rayerbazar" },
      { name: "Hazaribagh" },
      { name: "Kamrangirchar" },
      {
        name: "Motijheel",
        subAreas: ["Motijheel", "Paltan", "Segunbagicha"],
      },
      { name: "Ramna", subAreas: ["Ramna", "Shantinagar", "Eskaton", "Maghbazar"] },
      { name: "Gopibagh" },
      { name: "Malibagh" },
      { name: "Jatrabari", subAreas: ["Jatrabari", "Sabujbagh", "Mugda", "Jurain"] },
      { name: "Demra" },
      { name: "Shyampur" },
      { name: "Wari" },
      { name: "Gendaria" },
      {
        name: "Old Dhaka",
        subAreas: ["Lalbagh", "Sutrapur", "Kotwali", "Chawkbazar", "Islampur", "Bangshal"],
      },
      { name: "Turag" },
      { name: "Tongi" },
      { name: "Gazipur", subAreas: ["Gazipur Sadar", "Konabari", "Board Bazar", "Chandra"] },
      { name: "Savar", subAreas: ["Savar", "Ashulia", "Birulia", "Dhamrai"] },
      { name: "Keraniganj" },
      {
        name: "Narayanganj",
        subAreas: ["Narayanganj Sadar", "Siddhirganj", "Fatullah", "Bandar"],
      },
    ],
  },
  {
    label: "Chattogram",
    areas: [
      { name: "GEC Circle" },
      { name: "Khulshi", subAreas: ["Khulshi", "Foy's Lake"] },
      { name: "Agrabad", subAreas: ["Agrabad", "Agrabad C/A"] },
      { name: "Halishahar", subAreas: ["Halishahar", "Halishahar Housing Estate"] },
      { name: "Nasirabad" },
      { name: "Panchlaish" },
      { name: "Chandgaon" },
      { name: "Bayezid" },
      { name: "Muradpur" },
      { name: "Oxygen" },
      { name: "Pahartali" },
      { name: "Chawkbazar (CTG)" },
      { name: "Kotwali (CTG)" },
      { name: "Patenga" },
      { name: "EPZ" },
      { name: "Bandar (CTG)" },
      { name: "Sitakunda" },
      { name: "Anwara" },
      { name: "Karnaphuli" },
      { name: "Boalkhali" },
      { name: "Hathazari" },
      { name: "Fatikchhari" },
      {
        name: "Cox's Bazar",
        subAreas: [
          "Cox's Bazar Sadar",
          "Kolatoli",
          "Laboni Point",
          "Sugandha Point",
          "Himchari",
          "Inani",
          "Marine Drive",
          "Teknaf",
        ],
      },
      {
        name: "Moheshkhali",
        subAreas: ["Moheshkhali Sadar", "Sonadia Island", "Gorakghata"],
      },
    ],
  },
  {
    label: "Other Divisions",
    areas: [
      { name: "Sylhet", subAreas: ["Zindabazar", "Amberkhana", "Shahjalal Upashahar"] },
      { name: "Khulna", subAreas: ["Khalishpur", "Sonadanga", "Boyra"] },
      { name: "Rajshahi", subAreas: ["Shaheb Bazar", "Uposhahar", "Kazla"] },
      { name: "Barishal", subAreas: ["Band Road", "Kaunia"] },
      { name: "Rangpur", subAreas: ["Jahaj Company More", "Shapla Chattar"] },
      { name: "Mymensingh", subAreas: ["Ganginarpar", "Chorpara"] },
      { name: "Comilla" },
    ],
  },
];
